### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by ansh** [hazae41/xswr#3]
I see that the only dependency is React, therefore this library should be compatible with React Native.

Just wanted to confirm this is the case -- if so, could you add this information to the README?

**Comment by hazae41** [comment]
I did not test it with React Native, but it should probably work

I can test it in a few days

**Comment by ansh** [comment]
Sounds good. I am looking forward to seeing your results.

**Comment by hazae41** [comment]
React Native works

You can test it right there

https://snack.expo.dev/@git/github.com/hazae41/xswr-example-expo

**Comment by ansh** [comment]
Great!

I would suggest adding that Snack to the README for future users :)

**Comment by hazae41** [comment]
Done, just click here

![](https://user-images.githubusercontent.com/4405263/199753858-e238cbaf-7209-4aad-8b76-79f15aa58d89.png)
